# Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: apps/v1
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#deployment-v1-apps
kind: Deployment
metadata:
  name: film
  labels:
    app: film
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector
  selector:
    matchLabels:
      app: film
  # Anzahl laufender Pods fuer das template
  replicas: 1
  # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
  template:
    metadata:
      labels:
        app: film
    # Spezifikation des Pod
    spec:
      serviceAccountName: acme-film
      containers:
        # https://kubernetes.io/docs/concepts/containers/images
        - image: docker.io/juergenzimmermann/film:1.0.0
          name: film
          # https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables
          # https://opensource.com/article/19/6/introduction-kubernetes-secrets-and-configmaps
          envFrom:
            # https://kubernetes.io/docs/concepts/configuration/configmap
            - configMapRef:
                name: film-env
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: password
          ports:
            - containerPort: 3000
          resources:
            # https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits
            # Mindestanforderung an Ressourcen:   kubectl top pod
            requests:
              # CPU-Ressourcen werden in "millicores" definiert, z.B. "500m" oder "1"
              cpu: 500m
              # Memory-Resources werden i.a. als "mebibyte" Wert definiert
              memory: 512Mi
            # Begrenzung der Ressourcen
            limits:
              cpu: 600m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            # Logdatei in einem Verzeichnis durch Mounting
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/log/node
              name: log-film
      volumes:
        - name: log-film
          # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
          hostPath:
            path: /run/desktop/mnt/host/c/Zimmermann/volumes/film
            type: Directory
